services:
  - type: web
    name: chargeflow-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python train.py
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: MONGODB_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
